### ISSUE TITLE
Create the Promethee Network.

### ISSUE THREAD

**Issue by PedroBSB** [lamfo-unb/RMCriteria#2]
Create the Promethee Network plot based on Gaia/Promethee,

**Comment by PedroBSB** [comment]
@monteirogustavo pode explicar como deve ser esse gráfico ? Daí eu assumo esse issue.

**Comment by monteirogustavo** [comment]
@PedroBSB o gráfico é desse modelo: https://imgur.com/a/B63eJ

**Comment by PedroBSB** [comment]
Valeu! Você consegue me explicar a lógica ? Para onde as setas devem ser direcionadas e a partir de quem ?

**Comment by monteirogustavo** [comment]
Começa na melhor ação, aí as setas são direcionadas da maior preferência pra menor. As que não têm direção é porque são incomparáveis (Phi+ maior e Phi- menor ou vice-versa).

**Comment by PedroBSB** [comment]
@monteirogustavo criei um arquivo PrometheeNetwork.R na pasta test. Lá tem uns exemplos de como usar o ggnetwork. O método já cria a rede baseada nas regras que você me disse. O que precisa fazer agora é deixar o gráfico mais interessante. Qualquer dúvida me avise.
